### ISSUE TITLE
wrong impact path

### ISSUE THREAD

**Issue by acid-maker** [duskwuff/Xilinx-ISE-Makefile#1]
Hi. I've noticed that there is wrong path in 'prog' rule for 'impact' tool.

Now there is:

$(XILINX)/impact -batch $(IMPACT_OPTS)

And it should be changed into:

$(XILINX)/bin/$(XILINX_PLATFORM)/impact $(IMPACT_OPTS)

because XILINX points to ISE directory not 'bin/XXX'. Also '-batch' should be removed here because it is already inside IMPACT_OPTS

**Comment by duskwuff** [comment]
Thanks for pointing this out!
